[package]

name = "testu01"
version = "0.0.1"
authors = ["Loïc Damien <loic.damien@dzamlo.ch>"]

[dependencies]

lazy_static = "1.4.0"
libc = "0.2"
rand = "0.8.5"

[dev-dependencies]
rand_xorshift = "0.3.0"